Upload lab 5
viktor-kindrat/lab5 pull request #1
Opened 2023-11-29 19:40 UTC by viktor-kindrat

A pull request to upload lab 5 from algos

2023-11-29 19:59 UTC, Karpde requested changes
Yon need to rewrite __repr__ method.
You need to add __str__ method.

2023-11-29 20:00 UTC, Karpde commented
The __repr__() should return a more information-rich, or official, string representation of an object. This method is called by the built-in repr() function. If possible, the string returned should be a valid Python expression that can be used to recreate the object.

2023-11-29 20:18 UTC, viktor-kindrat commented
> The **repr**() should return a more information-rich, or official, string representation of an object. This method is called by the built-in repr() function. If possible, the string returned should be a valid Python expression that can be used to recreate the object.

FIXED ✅

2023-11-29 20:18 UTC, viktor-kindrat commented
> Yon need to rewrite **repr** method. You need to add **str** method.

FIXED ✅

2023-11-29 20:21 UTC, Karpde approved these changes
Good job!

2024-01-13 14:51 UTC, zveres-ss commented on lab5.py
> +    for el in store.sort_by_price():
what el var name means?

2024-01-13 15:06 UTC, viktor-kindrat commented on lab5.py
> +    for el in store.sort_by_price():
El variable in this case means a phone inctance in list. Varialbe was renamed to more clear varinat ✅

2024-01-23 13:44 UTC, closed without merging